jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  authorizationStrategy: unsecured
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  slaveAgentPort: 50000
  disableRememberMe: false
  numExecutors: 4
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
jobs:
  - file: /var/jenkins_home/job_files/testpy.groovy