apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-admin
      # automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        # runAsGroup: 1000
      containers:
        - image: jenkins/jenkins:2.439-jdk21
        # - image: steve353/jenkins:k8s-v0.3
        # - image: jenkins/jenkins:lts
          imagePullPolicy: IfNotPresent
          name: jenkins
          ports:
          - containerPort: 8080
            name: http-port
          - containerPort: 50000
            name: jnlp-port
          env:
          - name: CASC_JENKINS_CONFIG
            value: /var/jenkins
          - name: JAVA_OPTS
            value: -Djenkins.install.runSetupWizard=false -Dhudson.lifecycle=hudson.lifecycle.ExitLifecycle -Djenkins.model.Jenkins.slaveAgentPort=50000 -Duser.home=/var/jenkins_home
          volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-data
          - name: casc
            mountPath: /var/jenkins
      initContainers:
      - name: install-plugins
        image: steve353/jenkins:k8s-v0.3
        command:
          - /bin/sh
          - "-c"
          - "mkdir /var/jenkins_home/plugins ; jenkins-plugin-cli --verbose --war /usr/share/jenkins/jenkins.war --plugin-file /usr/share/jenkins/ref/plugins.txt --plugin-download-directory /var/jenkins_home/plugins"
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-data
          - name: plugins
            mountPath: /usr/share/jenkins/ref
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins-pvc
      - name: casc
        configMap:
          name: casc
          items:
          - key: jcasc.yaml
            path: jenkins.yaml
      - name: plugins
        configMap:
          name: plugins
          items:
          - key: plugins.txt
            path: plugins.txt